name: Ruby version

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ruby-version:
    name: "test that script: works with Ruby ${{ matrix.ruby_version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version: [2.7.8, 3.0.7, 3.1.7, 3.2.9, 3.3.9]
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          script: |
            github.contributors('k1LoW/github-script-ruby', true).each { |c| puts c.login }
            exit 1 unless github.contributors('k1LoW/github-script-ruby', true).one? { |c| c.login == 'k1LoW' }
          ruby-version: ${{ matrix.ruby_version }}
          debug: true
